name: Push New Image

on: [push]

env:
  IMAGE_REPO: jeeaaasustest
  IMAGE_NAME: youtube-dl

jobs:
  Push-New-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Get environment variables
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Set tag
        run: |
          if echo "$CI_ACTION_REF_NAME_SLUG" == 'master'
          then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$CI_ACTION_REF_NAME_SLUG" >> $GITHUB_ENV
          fi

      - name: Print image tag
        run: |
          echo "Branch: $CI_ACTION_REF_NAME_SLUG"
          echo "Image Tag: ${{ env.IMAGE_TAG }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
